### ISSUE TITLE
Preferences not available via extension site

### ISSUE THREAD

**Issue by sanjarcode** [mheine/gnome-shell-spotify-label#13]
Preferences are not available when the extension is installed via https://extensions.gnome.org/
Only 3 files are downloaded in the extension folder, extension.js, metadata.json and stylesheet.css.
Please update the code on the site.

**Comment by devNan0** [comment]
@sanjarcode witch gnome-shell version do you have?
`gnome-shell --version`

**Comment by sanjarcode** [comment]
GNOME Shell 3.28.4

**Comment by devNan0** [comment]
Than we have the same "issue".
See: https://github.com/mheine/gnome-shell-spotify-label/issues/15

**Comment by mheine** [comment]
The code on the website has been updated, but with GNOME v3.36.4. If you absolutely cannot update to GNOME 3.36.4, then I would recommend that you install this extension "manually" using the steps in the README, or by just copying over the new contents of the file. I'm closing this issue, but feel free to re-open it if you encounter more problems :)
