### ISSUE TITLE
Schemas in wrong folder / extensions.gnome.org zip outdated?

### ISSUE THREAD

**Issue by devNan0** [mheine/gnome-shell-spotify-label#14]
Hey,

if you go to: https://extensions.gnome.org/extension/2603/spotify-label/
and select `Shell version: 3.36.4` and `Extension version: 3`

you will get an archive where https://github.com/mheine/gnome-shell-spotify-label/issues/8 is still not fixed.
The `gschemas.compiled` and `org.gnome.shell.extensions.spotifylabel.gschema.xml` files are still in the root folder and not in the `schemas` folder.

Could you update the archive on the extensions page?

**Comment by mheine** [comment]
Hi,
Apologies for the delay, I've uploaded a new version to the GNOME extension store this weekend, and I'm waiting for it to be approved - I'll keep you posted on when it does!

**Comment by devNan0** [comment]
No worries, just wanted to ask :)
Thanks for the update.

**Comment by mheine** [comment]
The website has been updated with the new version (let's just ignore the fact that it took me several months to get it completed :grimacing: ) - closing this issue :slightly_smiling_face:
