### ISSUE TITLE
Question: Shell version 3.36.4 really required?

### ISSUE THREAD

**Issue by devNan0** [mheine/gnome-shell-spotify-label#15]
Hey,

first of all.. i totally love this extension :)
This is more a question than an issue, so please forgive me...

Version 3 has defined gnome shell version `3.36.4` in its `manifest.json`
Is this really required? Or could we lower this to something like `3.30.2`
I´m asking because on Debian Buster `3.30.2` is the highest version i can get without adding the backports ore something.
I tried installing the latest version of this extension manually and it works fine AFAIK.

Main thing i need/want is new added settings of the extension so i can tweak it a bit.

**Comment by mheine** [comment]
Hey, I'm sorry for the late response - and no worries about it being more of a question than an issue. I'm somewhat against going back to older versions for later releases, so if you were able to install the latest version manually (including the settings you wanted), is that acceptable to you? If you feel that this is an important issue I suppose we could look into creating a tagged release for `3.30.2`, but I'd prefer to not go back if possible. Thank you for the praise in any case! :tada:

**Comment by devNan0** [comment]
Because i mange my desktops with ansible, I already install the latest version manually.
And I understand that you don't what to go back to older versions.

But for all other Debian users, this could be a problem.
See: https://tracker.debian.org/pkg/gnome-shell

So for me this isn't an issue any more and can be closed.

BTW: Thanks for that extension, I really love it :)

**Comment by mheine** [comment]
Looks like `3.38.2` is in testing, after which this shouldn't be an issue anymore - but who knows when that could be. I don't run Debian myself, so thanks for the clarification! Closing the issue :slightly_smiling_face:

**Comment by devNan0** [comment]
Testing means the next major release of Debian, which would be Debian 11 where the exact release date needs yet to be defined.
Debian 10 (current major release) won't get much newer than 3.30.

See: https://endoflife.date/debian
