### ISSUE TITLE
Redirect to Spotify

### ISSUE THREAD

**Issue by harsh-weather** [mheine/gnome-shell-spotify-label#2]
Hi, is there anyway you could add a feature which allows a drop down display which opens up when clicked on the label? With all the buttons (pause, play next, rewind), album cover, and a button to redirect to Spotify app?

**Comment by mheine** [comment]
Heya! At the moment I have no plans of extending this extension; at most I'd add a play/pause when the label is clicked, but the main point was for it to just be a label, and not much else. I would suggest using a more all-round extension, have you looked into the MPRIS Indicator Extension? (https://extensions.gnome.org/extension/1379/mpris-indicator-button/)

**Comment by harsh-weather** [comment]
Could you point me in the direction how i can fork your repo and do so on my own?
(Like what languages, concepts I should learn etc.)
PS. (Currently, am a Linux noob)

**Comment by mheine** [comment]
No worries, we all start somewhere! 
Forking the repo is done on GitHub (top right), and then you'll be able to clone your version of the repo, and you'll be able to make any changes you desire.

Regarding extending the project, the language to use is JS. I would recommend reading through [p-e-w's boilerplate project](https://github.com/p-e-w/argos) - there's a lot of information, but it's well-written, and his project is probably a better baseline for what you want to do (you could start by using his templates, and then looking at my code to add the actual Spotify text). If video tutorials are more your thing, I'd probably recommend the [How to create a GNOME extension series](https://www.youtube.com/watch?v=iMyR5lJf7dU) in 7 parts. Hope this helps! :)
