### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by pesader** [mheine/gnome-shell-spotify-label#20]
When I attempted to download the extension via [Gnome Extensions](https://extensions.gnome.org/#) I got an error right away and the following log:

```
The settings of extension gnomespotifylabel@mheine.github.com had an error:

GLib.FileError: Failed to open file “/home/pedro/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:

buildPrefsWidget@/home/pedro/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/prefs.js:15:44
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

## Update (that was quick)

It looks like user [Andorius](https://extensions.gnome.org/accounts/profile/Andorus) solved the problem with the following instructions:
> Works great in Ubuntu 20.0.4, but needs some manual massaging to run. Essentially you need to create the "schemas" sub-folder that wasn't created by the installation, then move the gschemas.compiled folder into it, then restarting GNOME or your PC so the extension picks it up. Full steps are below.
If you like the terminal, run this command after you install the extension:

```
mkdir ~/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/schemas && mv ~/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/gschemas.compiled ~/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/schemas/
```

> Then, restart GNOME with Alt+F2 > "r" > Enter, or this terminal command (works for me in GNOME 3.36.8):
```
busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")'
```
> If you want do do this in GUI, use the below.
> 1. Install Extension from this page. You will get an error, this is fine for now.
> 2. Open your terminal or file explorer and navigate to home/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/
> If you do not see .local, you can click on the hamburger/other menu and click "show hidden files" or use the terminal command I placed above these steps (Open terminal with Ctrl+Alt+T).
> 3. Create a new sub-folder named "schemas" (all lower-case)
> 4. Move the file "gschemas.compiled" from the parent folder into the folder you just created.
> 5. Restart Gnome with Alt+F2, type "r" (no quotes) and push enter. Gnome will restart and the extension will work as expected.

Thanks for developing this awesome piece of software!

**Comment by mheine** [comment]
The extension has been updated on the GNOME Extensions webpage. I'll close the issue since it should be fixed, but feel free to re-open if you run into more issues. Thanks for your kind words in any case! :tada:
