### ISSUE TITLE
Gnome 40 ?

### ISSUE THREAD

**Issue by ChTPwner** [mheine/gnome-shell-spotify-label#25]
Hello,

I am just wondering if you could simply add version 40 as an accepted version of Gnome of your extension and create a new release ?

I changed the metadata.json file on my machine to look like this, and it works flawlessly. 

```json
{
    "name": "Spotify Song Label", 
    "description": "Show the currently playing song on Spotify in the top bar", 
    "uuid": "gnomespotifylabel@mheine.github.com", 
    "shell-version": [
        "3.36.4", 
        "40"
     ] 
}
```
Thanks for your work, I really appreciate your extension.

**Comment by mheine** [comment]
Heya! I'm a bit hesitant of adding support for version 40 without testing it - I don't think anything should have changed in terms of this extension, but I'd have to look into it just to make sure. As soon as I (or someone else for that matter) get around to verifying that all features work as expected, then I can create a new release on the GNOME Extensions page. Thank you for the kind words! :tada:

**Comment by ChTPwner** [comment]
I understand. 
I can tell you in a few weeks if I met any issues with my settings.
None so far.

**Comment by ChTPwner** [comment]
Hi, quick follow up.

So the main functionnality (displaying the name and artist in the top bar) is OK.

But you are right,  there are some issues with he preferences menu: 
![image](https://user-images.githubusercontent.com/14848356/118776004-ccbd8400-b887-11eb-8f1c-9d07c302f898.png)

The settings of extension gnomespotifylabel@mheine.github.com had an error:
```
Error: No property margin on GtkGrid
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
buildPrefsWidget@/home/thibault/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/prefs.js:25:23
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
Let me know how I could help you with fixing this, if you wish

**Comment by ChTPwner** [comment]
I took a quick look to fix it and manage to correct the issue with only changing the "margin" property:

![image](https://user-images.githubusercontent.com/14848356/118779574-7ce0bc00-b88b-11eb-9452-2a8cc6400419.png)

It fixes the issue, but I do not know if this will work for Gnome versions < 40 since I do not have a computer with gnome 3.3x anymore.

![image](https://user-images.githubusercontent.com/14848356/118779635-88cc7e00-b88b-11eb-9da4-1fdf077b3fa7.png)

**Comment by raujonas** [comment]
I fixed it according to @ChTBoner 's changes in #27, the margin really seems to be the only issue. It works now with both older (<40) and newer (40+) versions, so you could both test it against your local version again :blush:. Hope this helps!

**Comment by ChTPwner** [comment]
Hi everyone,

It seems the metadata.json file has not been updated to account for gnome version 40 yet.

**Comment by mcmxcdev** [comment]
What is the process to download the new extension version? 
extensions.gnome.org still tells me incompatible. Or do you still need to release it?
