### ISSUE TITLE
Not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by harsh-weather** [mheine/gnome-shell-spotify-label#3]
Hey! Can you make it compatible with Ubuntu 20.04 Focal Fossa?

**Comment by mheine** [comment]
Heya! I'm not running 20.04 myself, but I can probably give it a go. What version of GNOME Shell are you using?

**Comment by harsh-weather** [comment]
Hi, my gnome version is 3.36.1

**Comment by raujonas** [comment]
I fixed it for 3.36, PR is coming very soon, just the last polish with the new settings view we already talked about @mheine
