### ISSUE TITLE
not working with spotify installed via snap

### ISSUE THREAD

**Issue by modularTaco** [mheine/gnome-shell-spotify-label#5]
Hi,

I'm running Fedora 31 and installed spotify via Snap (`spotify                1.1.26.501.gbe11e53b-15     41    latest/stable  spotify✓      -`)
Unfortunately the extension is not able to display any information about the currently played song.

Executing `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'` shows the following output:
```
method return time=1593712509.780259 sender=:1.40429 -> destination=:1.41180 serial=786 reply_serial=2
   variant       array [
         dict entry(
            string "mpris:trackid"
            variant                string "spotify:track:1BW2QdLe6RtJTMJDSYmg9w"
         )
         dict entry(
            string "mpris:length"
            variant                uint64 227440000
         )
         dict entry(
            string "mpris:artUrl"
            variant                string ""
         )
         dict entry(
            string "xesam:album"
            variant                string ""
         )
         dict entry(
            string "xesam:albumArtist"
            variant                array [
                  string ""
               ]
         )
         dict entry(
            string "xesam:artist"
            variant                array [
                  string ""
               ]
         )
         dict entry(
            string "xesam:autoRating"
            variant                double 0
         )
         dict entry(
            string "xesam:discNumber"
            variant                int32 0
         )
         dict entry(
            string "xesam:title"
            variant                string ""
         )
         dict entry(
            string "xesam:trackNumber"
            variant                int32 0
         )
         dict entry(
            string "xesam:url"
            variant                string "https://open.spotify.com/track/1BW2QdLe6RtJTMJDSYmg9w"
         )
      ]
```

So spotify does not provide any artist or title information, but the url does change on every track change
is there another way to get the currently played song information? Or do you have any idea why spotify does not provide this information via dbus in my case?

**Comment by modularTaco** [comment]
ok I found out that others had this problem if spotify notifications were disabled, either via UI or spotify prefs file. Neither is the case. Spotify notifications are enabled, but...they're empty too
![image](https://user-images.githubusercontent.com/37046961/86397629-7a419c00-bca4-11ea-9fd6-a2b366a30fee.png)

**Comment by modularTaco** [comment]
ok might not specifically be related to your gnome plugin, more to spotify itself. will close this issue.

**Comment by mheine** [comment]
Apologies for not responding earlier - but as you said, this seems to be a Spotify issue. Feel free to re-open the issue if you have any other questions or concerns :)
