### ISSUE TITLE
Hide label if Spotify is off

### ISSUE THREAD

**Issue by sanjarcode** [mheine/gnome-shell-spotify-label#9]
The extension works nicely if spotify is ON. But it clogs the top bar if Spotify is off. Can the label be turned off if spotify is closed.
![image](https://user-images.githubusercontent.com/48156230/98161906-7fd71900-1f06-11eb-82ec-f0bab1e89c37.png)

**Comment by raujonas** [comment]
@sanjarcode You can disable this feature by turning off "Friendly greeting" in the extension settings if you have a version greater 1:

![grafik](https://user-images.githubusercontent.com/25148277/98167425-58be1e80-1ee9-11eb-9b2f-e42c653f6277.png)

**Comment by mheine** [comment]
@sanjarcode If you're on v1 you can manually edit the extension file (`~/.local/share/gnome-shell/extensions/gnomespotifylabel@mheine.github.com/extension.js`) and set `FRIENDLY_GREETING` to `false`, and the restarting the extension (ALT + F2). Closing the issue for now, feel free to re-open if you have more questions :slightly_smiling_face:

**Comment by sanjarcode** [comment]
Got it, @mheine.
@raujonas, How did you open the setting GUI? 
The icon is absent in Gnome Tweak Tool. I'm using Ubuntu 18.04
